Fix doc build after using PBR
PBR was introduced in https://review.openstack.org/296847
causing Sphinx build in RPM buildroot to fail with
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?

Workaround it by using autosetup -S git

Change-Id: Ic6fcc9bf404d4864709c021e7b532e8952b3f9f2