Update patch set 1
Patch Set 1:

BuildError: package openstack-packstack not in list for tag cloud7-openstack-newton-candidate , requires cbs admin.

Patch-set: 1
Reviewer: Gerrit User 128 <128@270e2033-b340-4cff-9539-693957ebf0e7>
Label: Code-Review=0